# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("server_stats", first_run=peewee.BooleanField(default=True))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("server_stats", ["first_run"])
    """
    Write your rollback migrations here.
    """
