# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("users", support_logs=peewee.CharField(default=""))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["support_logs"])
    """
    Write your rollback migrations here.
    """
