# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "server_stats", waiting_start=peewee.BooleanField(default=False)
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("server_stats", ["waiting_start"])
    """
    Write your rollback migrations here.
    """
