# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("schedules", parent=peewee.IntegerField(null=True))
    migrator.add_columns("schedules", delay=peewee.IntegerField(default=0))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("schedules", ["parent"])
    migrator.drop_columns("schedules", ["delay"])
    """
    Write your rollback migrations here.
    """
