# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("users", preparing=peewee.BooleanField(default=False))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["preparing"])
    """
    Write your rollback migrations here.
    """
