# Generated by database migrator
import peewee


def migrate(migrator, db):
    migrator.rename_column("backups", "directories", "excluded_dirs")


def rollback(migrator, db):
    migrator.rename_column("backups", "excluded_dirs", "directories")
